const Dashboard = () => {
  return (
    <div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
      <div>ddk</div>
    </div>
  );
};
export default Dashboard;
